# Generated by Django 3.2.6 on 2021-08-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opros_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'ОТКРЫТЫЕ ВОПРОСЫ'), (2, 'ЗАКРЫТЫЕ ВОПРОСЫ')], null=True),
        ),
    ]
